name: Build and Deploy
on:
  push:
    branches:
      - deply-gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - run: np  ci
      - run: npm install
      - run: npm run build # runs `next build`
        env:
          NEXT_PUBLIC_BASE_PATH: '/wineup-web'
      - run: npm run export # runs `next export`
        env:
          NEXT_PUBLIC_BASE_PATH: '/wineup-web'
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: type nul > ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
